Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTBSportsDataWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerEMail { get; set; }
    }
}

Models/Customer_Actions.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTBSportsDataWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Actions
    {
        public int CustomerActionId { get; set; }
        public string CustomerAction { get; set; }
    }
}

Models/Districts.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTBSportsDataWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Districts
    {
        public Districts()
        {
            this.Municipality = new HashSet<Municipality>();
            this.Tournaments = new HashSet<Tournaments>();
        }
    
        public int DistrictId { get; set; }
        public Nullable<int> SportId { get; set; }
        public string DistrictName { get; set; }
    
        public virtual ICollection<Municipality> Municipality { get; set; }
        public virtual ICollection<Tournaments> Tournaments { get; set; }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NTBSportsDataWeb.Models;
using System.IO;

namespace NTBSportsDataWeb.Controllers
{
    public class CustomerController : Controller
    {
        private NTBSportsDataTestContext db = new NTBSportsDataTestContext();



        //
        // GET: /Customer/

        public ViewResult Index()
        {
            return View(db.Customers.ToList());
        }

        //
        // GET: /Customer/Details/5

        public ViewResult Details(int id)
        {
            Customer customer = db.Customers.Find(id);
            return View(customer);
        }

        //
        // GET: /Customer/Create

        public ActionResult Create()
        {
            /*string[] CustomerSteps = new string[] {"Kundeinfo", "Jobber", "Profil"};
            ViewBag.CustomerSteps = new SelectList(CustomerSteps);
             */
            ViewBag.CustomerSteps = new SelectList(db.CustomerActions.ToList(), "CustomerActionId", "CustomerAction");

            ViewBag.CustomerID = new SelectList(db.Customers, "CustomerId", "CustomerName");
            return View();
        }

        private bool ViewExists(string name)
        {
            ViewEngineResult result = ViewEngines.Engines.FindView(ControllerContext, name, null);
            return (result.View != null);
        }

        public ActionResult Choose(int CustomerId, int CustomerSteps)
        {
            if (ModelState.IsValid)
            {
                

                ViewBag.CustomerSteps = new SelectList(db.CustomerActions.ToList(), "CustomerActionId", "CustomerAction");

                ViewBag.CustomerID = new SelectList(db.Customers, "CustomerId", "CustomerName");
                
                // Get customer name and such
                Customer customer = db.Customers.Find(CustomerId);
                ViewBag.CustomerName = customer.CustomerName;

                // Now find the name of a possible partialview
                Customer_Actions ca = db.CustomerActions.Find(CustomerSteps);
                
                // Creating the PartialViewName
                string PartialViewName = "_" + ca.CustomerAction.ToString();

                if (ViewExists(PartialViewName))
                {


                    ViewBag.PartialViewName = PartialViewName;
                }
                
                switch (CustomerSteps)
                {
                    case 1: // KundeInfo
                        // MessageFormat messageFormat = db.MessageFormat.Find(CustomerId);
                        ViewBag.MessageFormats = new SelectList(db.MessageFormats, "FormatId", "Format");
                        ViewBag.CharacterSets = new SelectList(db.CharacterSets, "CharacterSetId", "CharacterSet");


                        

                        
                        
                        
                        break;

                    case 2: // Jobber
                        JobsModels jobs = new JobsModels();
                        ViewBag.Kommuner = new SelectList(db.Municipalities, "MunicipalityId", "MunicipalityName");
                        ViewBag.Kretser = new SelectList(jobs.getDistricts(), "DistrictId", "DistrictName");

                        break;

                    case 3:

                        break;
                }



                // Customer customer = db.Customers.Find(id);

            }
            return View("Create");

        }

        //
        // POST: /Customer/Create

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(customer);
        }

        //
        // GET: /Customer/Edit/5

        public ActionResult Edit(int id)
        {
            Customer customer = db.Customers.Find(id);
            return View(customer);
        }

        //
        // POST: /Customer/Edit/5

        [HttpPost]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        //
        // GET: /Customer/Delete/5

        public ActionResult Delete(int id)
        {
            Customer customer = db.Customers.Find(id);
            return View(customer);
        }

        //
        // POST: /Customer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/DistrictsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NTBSportsDataWeb.Models;

namespace NTBSportsDataWeb.Controllers
{ 
    public class DistrictsController : Controller
    {
        private NTBSportsDataTestContext db = new NTBSportsDataTestContext();

        //
        // GET: /Districts/

        public ViewResult Index()
        {
            return View(db.Districts.ToList());
        }

        //
        // GET: /Districts/Details/5

        public ViewResult Details(int id)
        {
            Districts districts = db.Districts.Find(id);
            return View(districts);
        }

        //
        // GET: /Districts/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Districts/Create

        [HttpPost]
        public ActionResult Create(Districts districts)
        {
            if (ModelState.IsValid)
            {
                db.Districts.Add(districts);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(districts);
        }
        
        //
        // GET: /Districts/Edit/5
 
        public ActionResult Edit(int id)
        {
            Districts districts = db.Districts.Find(id);
            return View(districts);
        }

        //
        // POST: /Districts/Edit/5

        [HttpPost]
        public ActionResult Edit(Districts districts)
        {
            if (ModelState.IsValid)
            {
                db.Entry(districts).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(districts);
        }

        //
        // GET: /Districts/Delete/5
 
        public ActionResult Delete(int id)
        {
            Districts districts = db.Districts.Find(id);
            return View(districts);
        }

        //
        // POST: /Districts/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Districts districts = db.Districts.Find(id);
            db.Districts.Remove(districts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Customer/Create.cshtml
@model NTBSportsDataWeb.Models.Customer


@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <fieldset>
        <legend>Customer</legend>
@using (Html.BeginForm("Create","Customer",FormMethod.Post,null))
{
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomerName)
            @Html.ValidationMessageFor(model => model.CustomerName)

            
            <input type="submit" value="Create" />

        </div>
    
    
}

@using (Html.BeginForm("Choose", "Customer", FormMethod.Get,null))
{

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerId, "Customer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CustomerID", string.Empty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerId, "CustomerSteps")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CustomerSteps", string.Empty)

            <input type="submit" value="Get" />
        </div>
    }

    <div id="partialView">
    


    @if (Request.QueryString.Count > 0) 
    {

        string PartialViewName = ViewBag.PartialViewName;
        
        if (PartialViewName != null) {
            @Html.Partial((string)ViewBag.PartialViewName);
        }
    }
    </div>

    </fieldset>




<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Customer/Delete.cshtml
@model NTBSportsDataWeb.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Customer</legend>

    <div class="display-label">CustomerName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomerName)
    </div>

    <div class="display-label">CustomerAddress</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomerAddress)
    </div>

    <div class="display-label">CustomerEMail</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomerEMail)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Customer/Details.cshtml
@model NTBSportsDataWeb.Models.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Customer</legend>

    <div class="display-label">CustomerName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomerName)
    </div>

    <div class="display-label">CustomerAddress</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomerAddress)
    </div>

    <div class="display-label">CustomerEMail</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CustomerEMail)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.CustomerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Customer/Edit.cshtml
@model NTBSportsDataWeb.Models.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Customer</legend>

        @Html.HiddenFor(model => model.CustomerId)

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomerName)
            @Html.ValidationMessageFor(model => model.CustomerName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomerAddress)
            @Html.ValidationMessageFor(model => model.CustomerAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CustomerEMail)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CustomerEMail)
            @Html.ValidationMessageFor(model => model.CustomerEMail)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Customer/Index.cshtml
@model IEnumerable<NTBSportsDataWeb.Models.Customer>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            CustomerName
        </th>
        <th>
            CustomerAddress
        </th>
        <th>
            CustomerEMail
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerEMail)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CustomerId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CustomerId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CustomerId })
        </td>
    </tr>
}

</table>

Views/Customer/_districts.cshtml
@model NTBSportsDataWeb.Models.Districts





Views/Customer/_jobber.cshtml
@model NTBSportsDataWeb.Models.JobsModels
<div id="info">Jobb-informasjon for kunde: <b>Kunde her viewbag</b></div>

<fieldset id="Postadresse" style="float:left; margin-left: 10px;">
<legend>Noe 1</legend>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    
    <div id="Kretser">
    
    </div>
<div class="editor-label">Kretser</div>
    <div class="editor-field">
        @Html.DropDownListFor(
        m => m.Districts,
        new SelectList(Model.Districts, "DistrictId", "DistrictName"),
        "[Velg et distrikt"]
        )
    </div>
   
    
<div class="editor-label">Kommuner</div>
    <div class="editor-field">
        @Html.DropDownList("Kommuner", string.Empty)
    </div>
    
}
</fieldset>

Views/Customer/_kundeinfo.cshtml
@model NTBSportsDataWeb.Models.Customer
           

<div id="info">Generell abonnement informasjon for kunde: <b>@ViewBag.CustomerName</b></div>

<fieldset id="Generelt" style="float:left;"><legend>Generelt</legend>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="editor-label">Navn på media</div>
    <div class="editor-field">
        <input type="text" name="MediaNavn" />
    </div>
    <br />
    
    <div class="editor-label">Kontaktnavn</div>
        <div class="editor-field"><input type="text" name="Kontaktnavn" value=""/>
    </div>
    <br />
    
    <div class="editor-label">Kontaktepost</div>
        <div class="editor-field"><input type="text" name="Kontaktepost" value=""/>
    </div>
    <br />           
}
</fieldset>

<fieldset id="Fakturaadresse" style="float:left; margin-left: 10px;"><legend>Noe 2</legend>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="editor-label">Brukernavn</div>
    <div class="editor-field">
        <input type="text" name="Brukernavn"/>
    </div>
    <br />
    
    <div class="editor-label">Passord</div>
    <div class="editor-field">
        <input type="password" name="Passord"/>
    </div>
    <br />
}
</fieldset>

<fieldset id="Postadresse" style="float:left; margin-left: 10px;"><legend>Noe 1</legend>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="editor-label">Format</div>
    <div class="editor-field">
        @Html.DropDownList("MessageFormats", string.Empty)
    </div>
    
    <div class="editor-label">Tegnsett</div>
    <div class="editor-field">    
        @Html.DropDownList("CharacterSets", string.Empty)
    </div>
    <br />
    
    <div class="editor-label">E-post adresse for mottak av resultater</div>
    <div class="editor-field">    
        <input type="text" name="epostmottak"/>
    </div>
    <br />
    
    <div class="editor-label">FTP-server adresse</div>
    <div class="editor-field">
        <input type="text" name="ftpserver"/>
    </div>
    <br />

    <div class="editor-label">FTP-server brukernavn</div>
    <div class="editor-field">    
        <input type="text" name="ftpbrukernavn"/>
    </div>
    <br />

    <div class="editor-label">FTP-server passord</div>
    <div class="editor-field">    
        <input type="text" name="ftppassord"/>
    </div>
    <br />

    <div class="editor-label">FTP-server mappe for resultatfiler</div>
    <div class="editor-field">    
        <input type="text" name="ftpfolder"/>
    </div>
    <br />
    
}
</fieldset>